# this_file: .github/workflows/build.yml
# CI Build Workflow - builds and tests on every push and PR

name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git describe

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Resolve version
      id: version
      shell: pwsh
      run: |
        # Call get-version.ps1 to derive version from git tags
        # Returns JSON with: base (X.Y.Z), semver (X.Y.Z-pre+build), tag (vX.Y.Z...)
        # Handles repos without tags by falling back to 0.0.0-dev.{count}+g{sha}
        $json = & scripts/get-version.ps1 -Format Json
        $info = $json | ConvertFrom-Json

        # Export to GITHUB_ENV for use in subsequent steps
        "VERSION_BASE=$($info.base)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "VERSION_SEMVER=$($info.semver)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "VERSION_TAG=$($info.tag)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

    - name: Display version
      shell: cmd
      run: |
        echo Building base version %VERSION_BASE%
        echo Building semantic version %VERSION_SEMVER%

    - name: Build
      shell: cmd
      run: build.cmd %VERSION_SEMVER%

    - name: Test executable exists
      shell: cmd
      run: |
        if not exist build\fontlift.exe (
          echo ERROR: fontlift.exe was not created
          exit 1
        )
        echo Build successful - fontlift.exe created

    - name: Test executable runs
      shell: cmd
      run: |
        build\fontlift.exe
        if %ERRORLEVEL% NEQ 0 (
          echo ERROR: fontlift.exe failed to run
          exit 1
        )

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fontlift-${{ env.VERSION_TAG }}
        path: build/fontlift.exe
        retention-days: 7
